version: '3'

services:
  backend:
    image: your_backend_image:tag
    ports:
      - "7000:7000"

  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      - backend
    environment:
      - GRPC_BACKEND_HOST=backend
      - GRPC_BACKEND_PORT=7000
